name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add remote server to known_hosts
      run: |
        ssh-keyscan -p 22 203.170.77.228 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -vvv -p 22 developer@203.170.77.228 "cd /home/developer/deploy-folder && git pull origin main"
